serverhttp:
  Port: :8080
  ReadTimeout: 10
  WriteTimeout: 10

postgres:
  PostgresqlHost: database
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: postgres
  PostgresqlSslmode: false
  PgDriver: pgx